[package]
name = "ezconfig-rs-derive"
version = "0.1.4"
edition = "2024"
description = "Procedural macro for ezconfig-rs"
license = "MIT"
repository = "https://github.com/Samujalphukan228/ezconfig"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"